project_id = "zggxtuyzynbrothraiaz"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.chat-diagnostico]
    verify_jwt = false
  [functions.gerar-pdf-diagnostico]
    verify_jwt = false
  [functions.ingest-knowledge]
    verify_jwt = false
  [functions.liberar-diagnosticos]
    verify_jwt = false
  [functions.process-diagnostico]
    verify_jwt = false
  [functions.search-knowledge]
    verify_jwt = false
  [functions.webhook-hotmart]
    verify_jwt = false
  [functions.webhook-kiwify]
    verify_jwt = false
